name: documentation

# build the documentation whenever there are new commits on main
on:
  workflow_dispatch: # manual
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6

      - name: Build docs
        run: |
          git clone https://github.com/nxtlo/syn/ # get theme
          uv run pdoc -o docs/ -t syn/rust/ src/* # build docs with theme

      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

      - id: deployment
        uses: actions/deploy-pages@v4
